# Site settings
title: ChipJS - A little Javascript framework.
email: hello@chip-js.org
description: > # this means to ignore newlines until "baseurl:"
  ChipJS is an ULTRA-lightweight Javascript framework.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chip-js.org" # the base hostname & protocol for your site
twitter_username: ChipJS
github_username:  chip-js

# Build settings
markdown: kramdown
